### PR TITLE
CodeForce Program Solution 

### PR DESCRIPTION
**Pull request by Rjndrkha**

### CODE REVIEW

**Comment by Rjndrkha** [comment]
done i already make a Readme.d please assign with hacktoberfest label

**Comment by larymak** [comment]
> done i already make a Readme.d please assign it with hacktoberfest label

Are you contributing for the sake of or are you doing it because you want to help other developers learn?

**Comment by larymak** [comment]
The file doesn't contain any detailed explanation, it's jus a link

**Comment by larymak** [comment]
Check out this guide on how to write a good README file.

https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/

**Pull request merged**
