### PR TITLE
pyttsx3 

### PR DESCRIPTION
**Pull request by KanakamSasikalyan**
Hi there,
Hope you are doing good! I added a new python module pyttsx3 [Text to Speech]. I have a great experience in it. This is the contribution from my side. Hope it will excites you a lot. I'll Contribute as much as I can
Thank you very much :)

### CODE REVIEW

**Comment by KanakamSasikalyan** [comment]
hi,
Why pyttsx3 not visible in the repo

**Comment by larymak** [comment]
I tried to go through your contributions and I didn't exactly understand it

What exactly does it entail?

**Comment by KanakamSasikalyan** [comment]
It is a module it will convert text to speech. It is a great module.pyttsx3 so i contributed. I developed my personal assistant using this....

**Comment by larymak** [comment]
Inside the folder can we have a specific code and not many files which are
empty?

**Comment by KanakamSasikalyan** [comment]
Actually, Those are Usage codes of the projects
Using those we can develop amazing stuff...
:)

**Comment by larymak** [comment]
Awesome, thanks!

**Pull request merged**
