### PR TITLE
contributed by Satarupa

### PR DESCRIPTION
**Pull request by Satarupa22-SD**

### CODE REVIEW

**Comment by larymak** [comment]
I can't see anything to merge from my end, kindly ensure that you uploaded the files correclty

**Comment by Satarupa22-SD** [comment]
Hi, please check the vid to Gif converter zip file in add-satarupa branch

**Comment by Satarupa22-SD** [comment]
Hi,
Please check again. I have added the file to the others folder now

**Comment by larymak** [comment]
Kindly include a README file with details on how to execute the code and some sample output

**Comment by Satarupa22-SD** [comment]
Sir, I have added the readme. Please merge my PR.

Thanks

**Pull request merged**
