### PR TITLE
Addition of number guessing game

### PR DESCRIPTION
**Pull request by Mannuel25**

### CODE REVIEW

**Comment by larymak** [comment]
check the README file it's causing a conflict while merging

**Comment by Mannuel25** [comment]
> check the README file it's causing a conflict while merging

Okay, I tried resolving the conflicts but I couldn't. Could you please allow me to make a new PR and add the project again?

**Comment by larymak** [comment]
> > check the README file it's causing a conflict while merging
> 
> Okay, I tried resolving the conflicts but I couldn't. Could you please allow me to make a new PR and add the project again?

Yes, please go ahead...

**Comment by Mannuel25** [comment]
> > > check the README file it's causing a conflict while merging
> > 
> > 
> > Okay, I tried resolving the conflicts but I couldn't. Could you please allow me to make a new PR and add the project again?
> 
> Yes, please go ahead...

Okay, thanks. I'll work on that now and make a new PR.

**Pull request closed without merging**
