### PR TITLE
Use random instead of randint

### PR DESCRIPTION
**Pull request by amankul**
Newly getting started to open source contributions. Saw other PRs for merge to main, not sure if master is maintained separately. Please advise.

### CODE REVIEW

**Comment by larymak** [comment]
The merging is into the main branch because it is the default branch, not the master.

**Comment by larymak** [comment]
After the changes you made, can you provide a sample output before we merge it?

**Comment by amankul** [comment]
@larymak sample screenshot attached. 
image

CONTRIBUTING.md talks about forking the branch from _master_ - maybe we need to change that to _main_ then.

**Comment by larymak** [comment]
Yes, I will change that.

**Pull request merged**
