### PR TITLE
InvenTree Updated

### PR DESCRIPTION
**Pull request by RonitDey020801**
Very sorry for the inconvenience caused. The 'InvenTree' I added earlier had some issue in it and hence it was not clickable.
I have updated the file and did all the necessary changes.
Please accept this pull request so that my project is contributed successfully.
Thank you.

### CODE REVIEW

**Comment by larymak** [comment]
Thank you for your contribution, Can you describe more about what InvenTree is about?

**Comment by RonitDey020801** [comment]
> 

InvenTree is an Inventory Management system that tracks orders or transactions of superstores as and when the customer buys any product. Along with this, it updates the inventory of the store in real time

**Comment by larymak** [comment]
Is it an entirely solo project on its own or is it integrated by other APIs, like the ones that will enable you to track your store transactions?

**Comment by RonitDey020801** [comment]
> Is it an entirely solo project on its own or is it integrated by other APIs, like the ones that will enable you to track your store transactions?

It is not integrated by any API. The transactions module is like a sub-section in this project

**Comment by larymak** [comment]
great

**Pull request merged**
