### PR TITLE
Create a web interface

### PR DESCRIPTION
**Pull request by a2937**
This is a draft pull request so my progress can be monitored. I've setup an initial project so far and plan to keep adding content till it is complete and is actually presentable on both phones and on desktop.

### CODE REVIEW

**Comment by larymak** [comment]
Hi, How is everything progressing from your end?

**Comment by a2937** [comment]
Screenshot 

Ironing out some of the details you are interested on the site and trying to determine the general style your community might be interested in so I can set a background.

**Comment by a2937** [comment]
It does however dynamically build out sort of cards for each major project, which is what I assumed you were after. Additional guidelines may be required.

**Comment by larymak** [comment]
I love the progress and appreciate every bit of it, In terms of guidelines we can have the projects listed in terms of categories, we can have the cards show like machine learning, Apps, web projects, etc.. and maybe have the contributors listed on the sidebar.

What do you think of that?

**Pull request closed without merging**
