### PR TITLE
Update Blackjack Condition

### PR DESCRIPTION
**Pull request by willberg845**
Blackjack function was also the win condition for getting 21. I changed the name of that function to check_Twenty_One(s) and added a check for if the number of cards == 2 to determine if the win condition should print that the player got blackjack. Otherwise, when a player receives 21, it prints "Hooray!......You made 21....etc." I did not add a condition to check that the cards are a 10 and an Ace because there is no other way to have 21 and only two cards. Thanks!

### CODE REVIEW

**Comment by larymak** [comment]
Can you provide instruction on how to play the game?

**Comment by willberg845** [comment]
https://bicyclecards.com/how-to-play/blackjack/

Here are the basic instructions on the game. It really depends on what you want this script to accomplish. If the goal is to show how to create a simple blackjack hand simulation without a betting portion then this looks great. The real game would include placing bets on each turn, creating the option to split hands, overall adding way more complexity to the program. I will update the READ ME to reflect how the script plays as is, while describing the assumptions and parts that are left out of the full game.

The original issue I responded to seemed to be a technicality that 'Blackjack' is only truly achieved if you are dealt 21 instead of if you get to 21 later in the hand.

**Comment by larymak** [comment]
not here in the conversation tab, maybe add a README file?

**Comment by willberg845** [comment]
https://github.com/larymak/Python-project-Scripts/pull/119

already did in this pull request. Please let me know if there is anything else I can do to help!

**Pull request merged**
