### PR TITLE
added cricket score predictor project

### PR DESCRIPTION
**Pull request by Vinayak119A**
I've added a cricket score predictor project under the folder "Machine learning projects", please take a gander and merge the 
the changes if everything is properly done.

### CODE REVIEW

**Comment by Vinayak119A** [comment]
@larymak please check it sir

**Comment by larymak** [comment]
How can one execute the code?

**Comment by Vinayak119A** [comment]
> How can one execute the code
streamlit run app.py
run this command in the pycharm terminal
Then you will get an url
In that url output will be displayed
@larymak sir

**Comment by Vinayak119A** [comment]
@larymak sir check the comment

**Comment by Vinayak119A** [comment]
@larymak sir please check it

**Pull request merged**
