### PR TITLE
Introduced genetic algorithms 

### PR DESCRIPTION
**Pull request by usmansafdarktk**
Introduced genetic algorithms along with a solution to a knapsack problem.

### CODE REVIEW

**Comment by larymak** [comment]
Hi @usmansafdarktk 
Can you kindly put the project in the correct folder and avoid creating additional folders.

**Comment by usmansafdarktk** [comment]
> Hi @usmansafdarktk Can you kindly put the project in the correct folder and avoid creating additional folders.

Hello, can you please guide me about the correct folder to place this algorithm in?

**Comment by usmansafdarktk** [comment]
> > Hi @usmansafdarktk Can you kindly put the project in the correct folder and avoid creating additional folders.
> 
> Hello, can you please guide me about the correct folder to place this algorithm in?

Hi, as per my understanding, I've moved the folder into Data Structures and Algorithms

**Comment by larymak** [comment]
Great

**Pull request merged**
