### PR TITLE
Update year to be dynamic from #139

### PR DESCRIPTION
**Pull request by vicinity123**
Update the hard-coded year was substituted by a more dynamic method. Using the **datetime** module, the *current year* can be found by using this:

```diff
+ from datetime import datetime


- Current_year = 2022
+ Current_year = datetime.now().year
```

### CODE REVIEW

**Comment by larymak** [comment]
the branch has conflicts, please resolve them by use of this commands:

Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b vicinity123-main main
git pull https://github.com/vicinity123/Python-project-Scripts.git main
Step 2: Merge the changes and update on GitHub.

git checkout main
git merge --no-ff vicinity123-main
git push origin main

**Comment by vicinity123** [comment]
I applied those commands and received an "Everything up to date" response from it. What do I do next?

**Comment by larymak** [comment]
push changes to the main repository of the original project, first pull the latest changes from the original to sync with your local. Currently, you are pushing to the forked repo on your account

**Comment by vicinity123** [comment]
I pulled and pushed the files and received an "Everything up to date" response. Is this the last step?

**Pull request closed without merging**
