### PR TITLE
django projects

### PR DESCRIPTION
**Pull request by RitiKSIBJr**
Chat system app added.

### CODE REVIEW

**Comment by larymak** [comment]
Some more details in the README would be helpful

**Comment by RitiKSIBJr** [comment]
Hi Hillary Nyakundi,
I have added the readme.md to project. You can check it out.

**Comment by larymak** [comment]
We need more info in the README file,

Are there any libraries that should be installed? If yes, could you include them in a requirements.txt file and show how to install the file in the README file.

Also, it is essential to add the sample output in the README file, so that when a person tries to run your project they can know what kind of output to expect.

**Comment by RitiKSIBJr** [comment]
More details have been added check it out

**Comment by larymak** [comment]
Good work on the additions.

**Pull request merged**
