### PR TITLE
Image Captcha Generator Utility Added

### PR DESCRIPTION
**Pull request by Dhrumil-Zion**
- I have added code
- I have added the readme.md file

### CODE REVIEW

**Comment by larymak** [comment]
Is it possible to get a sample of the code's output?

**Comment by larymak** [comment]
maybe you could add it to the code's README

**Comment by Dhrumil-Zion** [comment]
I have Added output file within folder

**Comment by Dhrumil-Zion** [comment]
I have added code output in the readme.md file.

**Pull request merged**
