### PR TITLE
Pong Game in python

### PR DESCRIPTION
**Pull request by FAHID-KHAN**
Hi ,I am new in the open source community .Its a small contribution from my side .Thanks

### CODE REVIEW

**Comment by larymak** [comment]
It will be really great if you could describe how to go about with the project

**Comment by FAHID-KHAN** [comment]
Well have u meant how to run the project or how its done ?

**Comment by larymak** [comment]
both will be really great

**Comment by FAHID-KHAN** [comment]
Hi lary I have uploaded a readme file with description of how this game works i hope it helps now

**Pull request merged**
